import { StyleSheet } from "react-native";
import { windowHeight } from "../../utility/size";
import colors from "../../utility/colors";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },

  header: {
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    paddingVertical: "5%",
    backgroundColor: "#FFFFFF",
  },

  actionItemsMainView: {
    width: "100%",
    paddingVertical: "2%",
    paddingHorizontal: 20,
  },
  actionItemsView: {
    width: "100%",
    backgroundColor: "#F9FAFB",
    paddingVertical: "5%",
    borderRadius: 10,
    paddingHorizontal: "5%",
    borderWidth: 1,
    borderColor: "#F3F4F6",
  },
  actionItemsText: { fontSize: 16, fontFamily: "Inter-Bold", color: "#111827" },

  borderBtnContainer: {
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.primaryPink,
    padding: 12,
    backgroundColor: colors.white,
    marginHorizontal: 12,
    marginTop: 10,
    borderRadius: 8,
    elevation: 4,
  },
  borderBtnContainerGold: {
    padding: 8,
    borderWidth: 0,
    elevation: 0,
    backgroundColor: null,
  },
  borderBtnTxt: {
    fontSize: 18,
    color: colors.primaryPink,
    fontFamily: "Inter-Medium",
  },
  borderBtnTxtGold: {
    fontSize: 18,
    color: colors.gold,
    fontFamily: "Inter-Medium",
  },
  topMainContainer: {
    height: windowHeight * 0.38,
    width: "95%",
    marginVertical: "5%",
    alignSelf: "center",
    // justifyContent: 'center',
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    // backgroundColor: 'red',
    // paddingVertical: '2%',
    // marginHorizontal: '3%',
  },
  imagePurchaseContainer: {
    flexDirection: "row",
    // alignItems: 'center',
    // justifyContent: 'space-between',
    height: windowHeight * 0.4,
    width: "100%",
  },
  imageMainContainer: {
    height: "100%",
    width: "47%",
  },
  circularIconContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: "5%",
    justifyContent: "space-around",
  },
  imageWrapper: {
    width: 120,
    height: 120,
  },
  imageProps: {
    width: 120,
    height: 120,
  },
  chatText: { fontSize: 22, color: "#FFFFFF" },

  chatContainer: {
    width: "80%",
    marginVertical: "3%",
    paddingVertical: "3%",
    alignSelf: "center",
    alignItems: "center",
    borderRadius: 40,
    backgroundColor: colors.primaryPink,
  },
  chatLaterContainer: {
    width: "80%",
    marginVertical: "3%",
    paddingVertical: "3%",
    alignSelf: "center",
    alignItems: "center",
    borderRadius: 40,
    borderWidth: 2,
    borderColor: colors.primaryPink,
  },

  settingsIconContainer: {
    flexDirection: "row",
    width: "100%",
    paddingVertical: "3%",
    alignItems: "center",
    borderBottomWidth: 1,
    justifyContent: "space-between",
    borderBottomColor: colors.softGrey,
  },
  contStyle: {
    width: "100%",
    alignSelf: "center",
    marginHorizontal: "5%",
    // backgroundColor: 'red',
  },
  purchaseUpgradeWrapper: {
    width: "50%",
    height: "100%",
    justifyContent: "space-between",
    // backgroundColor: 'green',
  },
  arrowIconView: {
    width: "12%",
    alignItems: "flex-end",
    justifyContent: "center",
    paddingVertical: "1%",
  },
  arrowIconImage: { width: "100%", height: 15 },
  purchaseUpgrade: {
    // width: '100%',
    height: "47%",
    // paddingVertical: '2%',
    justifyContent: "center",
    borderRadius: 20,
    backgroundColor: colors.white,
  },
  mySettingsContainer: {
    width: "90%",
    marginVertical: "5%",
    backgroundColor: colors.white,
    alignSelf: "center",
    borderRadius: 10,
    elevation: 3,
  },
  textIcon: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    paddingHorizontal: "5%",
  },
  verticalLine: {
    // width: 1,
    height: 18,
    marginHorizontal: "2%",
    borderWidth: 1,
    borderColor: "#374151",
    // backgroundColor: colors.mediumGrey,
  },
  settingsIconText: {
    // marginLeft: '3%',
    fontFamily: "Inter-Medium",
    fontSize: 14,
    color: "#374151",
  },
  mySettingsText: {
    marginBottom: "2%",
    fontSize: 20,
    fontFamily: "Inter-Bold",
    color: "#0C3677",
    alignSelf: "flex-start",
    backgroundColor: "red",
  },
});
