/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-2",
  aws_cognito_identity_pool_id: "us-east-2:ae85c97d-ed50-44da-8834-2f3b457bf8e9",
  aws_cognito_region: "us-east-2",
  aws_user_pools_id: "us-east-2_buLAJyTs3",
  aws_user_pools_web_client_id: "63258ddc5h2p76328ljg5lebq9",
  oauth: {
    domain: "rishtaaunty.auth.us-east-2.amazoncognito.com",
    scope: ["phone", "email", "openid", "profile", "aws.cognito.signin.user.admin"],
    redirectSignIn: "rishtaaunty://",
    redirectSignOut: "rishtaaunty://",
    responseType: "code"
  },
  federationTarget: "COGNITO_USER_POOLS",
  aws_cognito_username_attributes: ["EMAIL", "PHONE_NUMBER"],
  aws_cognito_social_providers: ["FACEBOOK", "GOOGLE", "APPLE"],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: []
  },
  aws_cognito_verification_mechanisms: ["EMAIL"]
};

export default awsmobile;
